name: get_pet
description: "Get Pet"
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  get_it: 7.6.7
  logger: 2.1.0
  go_router: 13.2.1

  # Localizations
  intl: any
  flutter_localizations:
    sdk: flutter

  # Storage
  shared_preferences: 2.2.2
  flutter_secure_storage: 9.0.0
  path: 1.9.0

  # Network
  http: 1.2.1
  #  mysql_client: 0.0.27
  mysql_utils: 2.1.4

  # State
  provider: 6.1.2
  control: 0.0.2

  # Utils
  path_provider: 2.1.2
  share_plus: 8.0.2
  package_info_plus: 6.0.0
  device_info_plus: 10.0.1
  connectivity_plus: 6.0.1
  uuid: 4.4.0
  open_settings_plus: 0.3.1
  image_picker: 1.1.1
  cached_network_image: 3.3.1
  clipboard: 0.1.3

  # Code generation
  json_annotation: 4.8.1

  # UI
  cupertino_icons: 1.0.6
  flutter_screenutil: 5.9.0
  flutter_svg: 2.0.10+1
  flutter_keyboard_visibility: 6.0.0
  mask_text_input_formatter: 2.9.0

  # Platform
  window_manager: 0.3.8
  windows_single_instance: 1.0.1

  # Firebase
  firebase_core: 2.31.0
  firebase_auth: 4.19.5
  firebase_storage: 11.7.5
  firebase_ui_auth: 1.14.0
  google_sign_in: 6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 3.0.1

  # Code generation
  build_runner: 2.4.8
  json_serializable: 6.7.1

  # Utils
  flutter_gen_runner: 5.4.0
  flutter_launcher_icons: 0.13.1
  # Usage example:
  # dart run rename getAppName --targets android,windows
  # dart run rename setAppName --targets android,windows --value "Get Pet"
  # dart run rename getBundleId --targets android,windows
  # dart run rename setBundleId --targets android,windows --value "ru.usatova_od.get_pet"
  rename: 3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

flutter_gen:
  output: lib/app/assets/
  integrations:
    flutter_svg: true

# To recreate the application icons after changing configuration, run the command:
# `dart run flutter_launcher_icons`
flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  #  adaptive_icon_background: "assets/images/app_icon_background.png"
  #  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"
  #  ios: true
  #  remove_alpha_ios: true
  windows:
    generate: true


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
